[
    [
        {"name": "Algebra", "credits": 2},
        {"name": "EDA", "credits": 2},
        {"name": "Networks", "credits": 2},
    ],
    [
        {"name": "Algebra", "credits": 2},
        {"name": "EDA", "credits": 2},
        {"name": "Networks", "credits": 2},
    ],
    [
        {"name": "Algebra", "credits": 2},
        {"name": "EDA", "credits": 2},
        {"name": "Networks", "credits": 2},
    ],
    None,
    [
        {"name": "Algebra", "credits": 2},
        {"name": "EDA", "credits": 2},
        {"name": "Networks", "credits": 2},
    ],
    [
        {"name": "Algebra", "credits": 2},
        {"name": "EDA", "credits": 2},
        {"name": "Calculus", "credits": 2},
    ],
    [
        {"name": "Algebra", "credits": 2},
        {"name": "EDA", "credits": 2},
        {"name": "Calculus", "credits": 2},
    ],
    None,
    [
        {"name": "Algebra", "credits": 2},
        {"name": "EDA", "credits": 2},
        {"name": "Calculus", "credits": 2},
    ],
    [
        {"name": "Algebra", "credits": 2},
        {"name": "EDA", "credits": 2},
        {"name": "Databases", "credits": 2},
    ],
    None,
    [
        {"name": "Algebra", "credits": 2},
        {"name": "EDA", "credits": 2},
        {"name": "Databases", "credits": 2},
    ],
    None,
    [
        {"name": "Algebra", "credits": 2},
        {"name": "EDA", "credits": 2},
        {"name": "Physic", "credits": 2},
    ],
    None,
    None,
    [
        {"name": "Algebra", "credits": 2},
        {"name": "Networks", "credits": 2},
        {"name": "Calculus", "credits": 2},
    ],
    [
        {"name": "Algebra", "credits": 2},
        {"name": "Networks", "credits": 2},
        {"name": "Calculus", "credits": 2},
    ],
    None,
    [
        {"name": "Algebra", "credits": 2},
        {"name": "Networks", "credits": 2},
        {"name": "Calculus", "credits": 2},
    ],
    [
        {"name": "Algebra", "credits": 2},
        {"name": "Networks", "credits": 2},
        {"name": "Databases", "credits": 2},
    ],
    None,
    [
        {"name": "Algebra", "credits": 2},
        {"name": "Networks", "credits": 2},
        {"name": "Databases", "credits": 2},
    ],
    None,
    [
        {"name": "Algebra", "credits": 2},
        {"name": "Networks", "credits": 2},
        {"name": "Physic", "credits": 2},
    ],
    None,
    None,
    [
        {"name": "Algebra", "credits": 2},
        {"name": "Calculus", "credits": 2},
        {"name": "Databases", "credits": 2},
    ],
    None,
    [
        {"name": "Algebra", "credits": 2},
        {"name": "Calculus", "credits": 2},
        {"name": "Databases", "credits": 2},
    ],
    None,
    [
        {"name": "Algebra", "credits": 2},
        {"name": "Calculus", "credits": 2},
        {"name": "Physic", "credits": 2},
    ],
    None,
    None,
    None,
    [
        {"name": "Algebra", "credits": 2},
        {"name": "Databases", "credits": 2},
        {"name": "Physic", "credits": 2},
    ],
    None,
    None,
    None,
    None,
    None,
]
